# -*- coding: utf-8 -*-
"""FINAL DM _NUR FAIZAH AZ ZAHRAH.ipynb

“Analisis Segmentasi Penjualan Tiket Pesawat Menggunakan Agglomerative Clustering dan Ensemble Regression(Ridge, Lasso, dan ElasticNet”

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IX8lbzF95uGoxROcmnZOAcr0bcS4hb_a
"""

# Import library
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import io
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.cluster import AgglomerativeClustering
from sklearn.decomposition import PCA
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, r2_score

"""Pada bagian awal Kode ini berfungsi untuk mengimpor dan menyiapkan library yang dibutuhkan dalam proses analisis data, mulai dari pengolahan dan pembersihan dataset menggunakan pandas dan NumPy, pembuatan visualisasi dengan Matplotlib dan Seaborn, tahap praproses data seperti encoding dan scaling, penerapan Agglomerative Clustering untuk pengelompokan data, penggunaan PCA untuk visualisasi hasil clustering, penerapan ensemble regression menggunakan Ridge, Lasso, dan ElasticNet, serta evaluasi performa model regresi menggunakan metrik Mean Squared Error (MSE) dan R² Score."""

# 1. DATA CLEANING
st.subheader("Data Cleaning")

st.write("Ukuran data awal:", df.shape)
st.write("Missing value per kolom:")
st.write(df.isnull().sum())

jumlah_duplikat = df.duplicated().sum()
st.write("Jumlah data duplikat sebelum cleaning:", jumlah_duplikat)

df = df.drop_duplicates()
st.write("Jumlah data duplikat setelah cleaning:", df.duplicated().sum())

if "Date" in df.columns:
    df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

st.subheader("Contoh data kolom Date setelah konversi ke datetime")
df_date_tampil = df[["Date"]].copy()
df_date_tampil["Date"] = df_date_tampil["Date"].dt.strftime("%Y-%m-%d %H:%M:%S")
st.dataframe(df_date_tampil.head())

st.write("Ukuran data setelah cleaning:", df.shape)

# 2. ENCODING DATA KATEGORIK
st.subheader("Encoding Data Kategorik")

df_encoded = df.copy()
encoder = LabelEncoder()

for col in df_encoded.select_dtypes(include="object").columns:
    df_encoded[col] = encoder.fit_transform(df_encoded[col])

st.write("Contoh 5 baris data setelah encoding:")
st.dataframe(df_encoded.head())

st.download_button(
    label="Download Data Encoding",
    data=df_encoded.to_csv(index=False),
    file_name="data_encoded.csv",
    mime="text/csv"
)

# 3. SCALING DATA (NUMERIC ONLY)
st.subheader("Scaling Data")

datetime_cols = df_encoded.select_dtypes(include=["datetime64[ns]"]).columns
df_numeric = df_encoded.drop(columns=datetime_cols)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_numeric)

st.write("Jumlah fitur setelah scaling:", X_scaled.shape)

# ===============================
# IMPORT LIBRARY
# ===============================
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import io

from sklearn.metrics import silhouette_samples
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.cluster import AgglomerativeClustering
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, r2_score

# ===============================
# CONFIG STREAMLIT
# ===============================
st.set_page_config(page_title="UAS Data Mining", layout="wide")
st.title("Analisis Clustering dan Regresi Ensemble")

# ===============================
# LOAD DATA
# ===============================
uploaded_file = st.file_uploader(
    "Upload dataset CSV",
    type=["csv"]
)

if uploaded_file is None:
    st.info("Silakan upload file CSV untuk memulai analisis")

else:
    df = pd.read_csv(uploaded_file)

    st.subheader("Data Awal")
    st.dataframe(df.head())


# ===============================
# DATA CLEANING
# ===============================
df = df.drop_duplicates()
if "Date" in df.columns:
    df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

# ===============================
# ENCODING
# ===============================
df_encoded = df.copy()
encoder = LabelEncoder()
for col in df_encoded.select_dtypes(include="object").columns:
    df_encoded[col] = encoder.fit_transform(df_encoded[col])

# ===============================
# FEATURE ENGINEERING (DATE)
# ===============================
df_encoded["Month"] = df_encoded["Date"].dt.month
df_encoded["Day"] = df_encoded["Date"].dt.day
df_encoded["DayOfWeek"] = df_encoded["Date"].dt.dayofweek

# ===============================
# SCALING
# ===============================
numeric_cols = df_encoded.select_dtypes(include=[np.number]).columns
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_encoded[numeric_cols])

# =====================================================
# ANALISIS 1: CLUSTERING SAJA (AGGLOMERATIVE)
# =====================================================
st.header("🔵 Analisis Clustering (Agglomerative)")

cluster_model = AgglomerativeClustering(n_clusters=3)
df_encoded["Cluster"] = cluster_model.fit_predict(X_scaled)

st.write("Distribusi Cluster:")
st.write(df_encoded["Cluster"].value_counts())

# PCA CLUSTERING
pca_cluster = PCA(n_components=2)
X_pca_cluster = pca_cluster.fit_transform(X_scaled)
df_encoded["PCA1"] = X_pca_cluster[:, 0]
df_encoded["PCA2"] = X_pca_cluster[:, 1]

fig_c, ax_c = plt.subplots()
sns.scatterplot(
    data=df_encoded,
    x="PCA1",
    y="PCA2",
    hue="Cluster",
    palette="Set2",
    ax=ax_c
)
ax_c.set_title("PCA Clustering (Agglomerative)")
st.pyplot(fig_c)

buf_c = io.BytesIO()
fig_c.savefig(buf_c, format="png", bbox_inches="tight")
buf_c.seek(0)
st.download_button(
    "Download Visualisasi PCA Clustering",
    buf_c,
    "pca_clustering.png",
    "image/png"
)


st.subheader("Evaluasi Clustering (Silhouette Score)")

silhouette_vals = silhouette_samples(X_scaled, df_encoded["Cluster"])
df_encoded["Silhouette"] = silhouette_vals

cluster_eval = (
    df_encoded
    .groupby("Cluster")
    .agg(
        Jumlah_Data=("Cluster", "count"),
        Silhouette_Score=("Silhouette", "mean")
    )
    .reset_index()
)

st.dataframe(cluster_eval)

# =====================================================
# ANALISIS 2: REGRESI + ENSEMBLE
# =====================================================
st.header("🟢 Analisis Regresi + Ensemble")

target_column = "Ticket_Quantity"
results = []

for c in sorted(df_encoded["Cluster"].unique()):
    data_c = df_encoded[df_encoded["Cluster"] == c]

    X = data_c.drop(columns=[target_column, "Cluster", "PCA1", "PCA2"], errors="ignore")
    y = data_c[target_column]

    X = X.select_dtypes(include=[np.number])

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    ridge = Ridge(alpha=1.0)
    lasso = Lasso(alpha=0.01)
    elastic = ElasticNet(alpha=0.01, l1_ratio=0.5)

    ridge.fit(X_train, y_train)
    lasso.fit(X_train, y_train)
    elastic.fit(X_train, y_train)

    y_pred = (
        ridge.predict(X_test)
        + lasso.predict(X_test)
        + elastic.predict(X_test)
    ) / 3

    results.append({
        "Cluster": c,
        "Jumlah_Data": len(data_c),
        "MSE": mean_squared_error(y_test, y_pred),
        "R2_Score": r2_score(y_test, y_pred)
    })

st.subheader("Hasil Ensemble Regresi")

regression_result = pd.DataFrame([
    {
        "MSE": mean_squared_error(y_test, y_pred),
        "R2_Score": r2_score(y_test, y_pred),
        "Jumlah_Data": len(df_encoded)
    }
])

st.dataframe(regression_result)


# OUTPUT REGRESI
result_df = pd.DataFrame(results)
st.subheader("Hasil Evaluasi Regresi Ensemble")
st.dataframe(result_df)

# PCA REGRESI (VISUALISASI SAJA)
fig_r, ax_r = plt.subplots()
sns.scatterplot(
    data=df_encoded,
    x="PCA1",
    y="PCA2",
    hue="Cluster",
    palette="Set1",
    ax=ax_r
)
ax_r.set_title("PCA untuk Analisis Regresi Ensemble")
st.pyplot(fig_r)

buf_r = io.BytesIO()
fig_r.savefig(buf_r, format="png", bbox_inches="tight")
buf_r.seek(0)
st.download_button(
    "Download Visualisasi PCA Regresi",
    buf_r,
    "pca_regresi_ensemble.png",
    "image/png"
)

