# -*- coding: utf-8 -*-
"""FINAL DM _NUR FAIZAH AZ ZAHRAH.ipynb

“Analisis Segmentasi Penjualan Tiket Pesawat Menggunakan Agglomerative Clustering dan Ensemble Regression(Ridge, Lasso, dan ElasticNet”

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IX8lbzF95uGoxROcmnZOAcr0bcS4hb_a
"""

# Import library
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.cluster import AgglomerativeClustering
from sklearn.decomposition import PCA
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, r2_score

"""Kode ini berfungsi untuk mengimpor dan menyiapkan library yang dibutuhkan dalam proses analisis data, mulai dari pengolahan dan pembersihan dataset menggunakan pandas dan NumPy, pembuatan visualisasi dengan Matplotlib dan Seaborn, tahap praproses data seperti encoding dan scaling, penerapan Agglomerative Clustering untuk pengelompokan data, penggunaan PCA untuk visualisasi hasil clustering, penerapan ensemble regression menggunakan Ridge, Lasso, dan ElasticNet, serta evaluasi performa model regresi menggunakan metrik Mean Squared Error (MSE) dan R² Score."""


# CONFIG STREAMLIT
# =====================================================
st.set_page_config(page_title="UAS Data Mining", layout="wide")
st.title("Clustering + Ensemble Regression")
st.write("Agglomerative Clustering dan Ensemble Regression (Ridge, Lasso, ElasticNet)")

# LOAD DATA (GOOGLE COLAB)
uploaded_file = st.file_uploader(
    "Upload dataset CSV (penjualan tiket pesawat)",
    type=["csv"]
)

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)

    st.subheader("Data Awal")
    st.dataframe(df.head())
else:
    st.info("Silakan upload file CSV untuk memulai analisis.")

"""Kode ini berfungsi untuk membaca dataset `penjualan_tiket_pesawat.csv` dari penyimpanan lokal Google Colab ke dalam sebuah DataFrame menggunakan Pandas, kemudian menampilkan lima baris pertama data sebagai gambaran awal struktur, isi kolom, dan contoh nilai pada dataset sebelum dilakukan proses pembersihan, analisis, clustering, maupun regresi.

"""

# 1. DATA CLEANING
st.subheader("🧹 Data Cleaning")
st.write("Ukuran data awal:", df.shape)
st.write("Missing value per kolom:")
st.write(df.isnull().sum())

df = df.drop_duplicates()
if "Date" in df.columns:
        df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
st.write("Ukuran data setelah cleaning:", df.shape)

"""Kode data cleaning tersebut digunakan untuk mengevaluasi dan memastikan kualitas dataset sebelum dilakukan analisis lebih lanjut, dengan cara menampilkan ukuran data awal, memeriksa jumlah missing value pada setiap kolom, mengecek keberadaan data duplikat, menghapus data duplikat jika ada, serta mengonversi kolom Date ke format datetime agar sesuai untuk analisis. Setelah proses pembersihan dilakukan, kode kembali menampilkan kondisi data untuk memastikan tidak ada perubahan yang tidak diinginkan, lalu menyimpan dataset hasil pembersihan ke dalam file data_cleaned.csv sebagai data siap olah.


Berdasarkan output yang dihasilkan, dataset memiliki 500 baris dan 9 kolom baik sebelum maupun sesudah proses data cleaning. Seluruh kolom, seperti Transaction_ID, City, Gender, Date, Ticket_Quantity, Ticket_Price, Airline, Payment_Method, dan Total, tidak memiliki missing value (nilai 0 di semua kolom) dan tidak ditemukan data duplikat (0). Hal ini menunjukkan bahwa dataset sudah dalam kondisi bersih dan konsisten, sehingga proses data cleaning tidak mengubah ukuran data. Dengan demikian, dataset tersebut layak dan siap digunakan untuk tahap analisis selanjutnya seperti clustering dan regresi tanpa risiko bias akibat data kosong atau duplikasi.
"""


# 2. ENCODING DATA KATEGORIK
st.subheader("Encoding Data Kategorik")
df_encoded = df.copy()
encoder = LabelEncoder()
for col in df_encoded.select_dtypes(include="object").columns:
        df_encoded[col] = encoder.fit_transform(df_encoded[col])
st.dataframe(df_encoded.head())



# 3. SCALING DATA (NUMERIC ONLY)
st.subheader("Scaling Data")
datetime_cols = df_encoded.select_dtypes(include=["datetime64[ns]"]).columns
df_numeric = df_encoded.drop(columns=datetime_cols)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_numeric)



# 4. CLUSTERING (TANPA ENSEMBLE)
st.subheader("Clustering (Agglomerative)")
n_cluster = st.slider("Pilih jumlah cluster", 2, 5, 3)
cluster_model = AgglomerativeClustering(n_clusters=n_cluster)
df["Cluster"] = cluster_model.fit_predict(X_scaled)
st.write("Distribusi Cluster:")
st.write(df["Cluster"].value_counts())

"""Kode ini digunakan untuk melakukan encoding pada data kategorik, yaitu mengubah nilai bertipe object (seperti teks atau kategori) menjadi nilai numerik agar dapat diproses oleh algoritma machine learning. Proses diawali dengan menyalin dataset hasil data cleaning ke dalam variabel df_encoded untuk menjaga data asli tetap utuh. Selanjutnya, setiap kolom bertipe object diubah menggunakan LabelEncoder, sehingga setiap kategori unik direpresentasikan dalam bentuk angka. Setelah proses encoding selesai, dataset hasil transformasi disimpan ke dalam file data_encoded.csv sebagai data yang siap digunakan pada tahap scaling, clustering, dan regresi.


Output dari proses ini adalah dataset dengan struktur dan jumlah data yang sama seperti sebelumnya (500 baris dan 9 kolom), namun seluruh kolom kategorik seperti City, Gender, Airline, dan Payment_Method telah diubah menjadi nilai numerik. Perubahan ini tidak memengaruhi jumlah data, hanya mengubah representasi nilai agar sesuai dengan kebutuhan algoritma analisis. File data_encoded.csv yang dihasilkan menjadi bukti bahwa data kategorik telah berhasil dipreproses dan siap digunakan pada tahap pemodelan selanjutnya.
"""



# 5. PCA UNTUK VISUALISASI CLUSTER
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
df["PCA1"] = X_pca[:, 0]
df["PCA2"] = X_pca[:, 1]
fig1, ax1 = plt.subplots()
sns.scatterplot(
        x="PCA1",
        y="PCA2",
        hue="Cluster",
        data=df,
        palette="Set2",
        ax=ax1
    )
ax1.set_title("Visualisasi Clustering (PCA)")
st.pyplot(fig1)

"""Kode ini digunakan untuk melakukan reduksi dimensi data menggunakan Principal Component Analysis (PCA) dengan tujuan utama mempermudah visualisasi hasil clustering. PCA mereduksi data berdimensi tinggi menjadi dua komponen utama (PCA1 dan PCA2) yang tetap mempertahankan informasi variansi terbesar dari data asli. Hasil transformasi tersebut kemudian disimpan ke dalam DataFrame sebagai dua kolom baru, sehingga data dapat divisualisasikan dalam bentuk grafik dua dimensi tanpa menghilangkan pola utama yang terbentuk dari proses clustering.


Output dari proses ini adalah dua kolom baru, yaitu PCA1 dan PCA2, yang masing-masing merepresentasikan komponen utama pertama dan kedua dari hasil reduksi dimensi. Kedua kolom ini tidak mengubah jumlah baris data, melainkan hanya menambahkan informasi baru untuk keperluan visualisasi. Dengan adanya PCA1 dan PCA2, hasil clustering dapat divisualisasikan dalam bentuk scatter plot dua dimensi sehingga pemisahan antar cluster dapat diamati secara lebih jelas dan intuitif.
"""



# 6. ENSEMBLE REGRESSION (RIDGE + LASSO + ELASTICNET)
st.subheader("Ensemble Regression")

numeric_columns = df.select_dtypes(include=[np.number]).columns.tolist()
target_column = st.selectbox(
        "Pilih kolom target regresi",
        numeric_columns
    )

ensemble_results = []

for cluster in sorted(df["Cluster"].unique()):
        data_cluster = df[df["Cluster"] == cluster]

        if len(data_cluster) < 5:
            continue

        X = data_cluster.drop(
            columns=[target_column, "Cluster", "PCA1", "PCA2"],
            errors="ignore"
        )
        y = data_cluster[target_column]

        X = X.select_dtypes(include=[np.number])

        ridge = Ridge(alpha=1.0)
        lasso = Lasso(alpha=0.01)
        elastic = ElasticNet(alpha=0.01, l1_ratio=0.5)

        ridge.fit(X, y)
        lasso.fit(X, y)
        elastic.fit(X, y)

        y_pred = (
            ridge.predict(X) +
            lasso.predict(X) +
            elastic.predict(X)
        ) / 3

        ensemble_results.append({
            "Cluster": cluster,
            "Jumlah_Data": len(data_cluster),
            "MSE": mean_squared_error(y, y_pred),
            "R2_Score": r2_score(y, y_pred)
        })

regression_df = pd.DataFrame(ensemble_results)
st.subheader("Hasil Ensemble Regresi per Cluster")
st.dataframe(regression_df)


"""Kode ini digunakan untuk melakukan ensemble regression pada setiap cluster hasil clustering, dengan tujuan memprediksi nilai Ticket_Price secara lebih stabil dan akurat. Proses dimulai dengan memisahkan data berdasarkan label cluster, kemudian untuk setiap cluster dilakukan pemodelan regresi menggunakan tiga algoritma regresi berbeda, yaitu Ridge, Lasso, dan ElasticNet, tanpa menggunakan Linear Regression. Fitur numerik dipilih sebagai variabel input, sementara Ticket_Price dijadikan sebagai variabel target. Prediksi akhir diperoleh dengan cara merata-ratakan hasil prediksi dari ketiga model regresi (ensemble averaging), sehingga dapat mengurangi bias dari satu model tunggal. Kinerja model kemudian dievaluasi menggunakan Mean Squared Error (MSE) dan R² Score.


Output menunjukkan hasil evaluasi ensemble regression pada setiap cluster yang terbentuk dari proses clustering sebelumnya. Cluster 0 memiliki 202 data dengan nilai MSE sebesar 2.67×10¹⁰ dan R² Score 0.860, yang berarti model mampu menjelaskan sekitar 86% variasi harga tiket pada cluster tersebut. Cluster 1 berisi 122 data dengan MSE paling kecil (2.94×10⁹) dan R² Score tertinggi (0.976), menandakan bahwa model regresi bekerja sangat baik dan paling akurat pada cluster ini. Sementara itu, Cluster 2 memiliki 176 data dengan MSE sebesar 3.15×10¹⁰ dan R² Score 0.798, yang menunjukkan performa model masih baik namun tidak seoptimal cluster lainnya. Secara keseluruhan, nilai R² yang tinggi pada semua cluster membuktikan bahwa penggunaan ensemble regression (Ridge, Lasso, dan ElasticNet) efektif dalam memodelkan harga tiket pada masing-masing segmen data hasil clustering.
"""



# 7. VISUALISASI OUTPUT
# Distribusi data per cluster
st.subheader("Download Output")

st.download_button(
        "Download Hasil Clustering + Regresi",
        data=df.to_csv(index=False),
        file_name="hasil_clustering_ensemble_regresi.csv",
        mime="text/csv"
    )
st.download_button(
        "Download Hasil Regresi",
        data=regression_df.to_csv(index=False),
        file_name="hasil_ensemble_regresi.csv",
        mime="text/csv"
    )


"""Kode ini digunakan untuk memvisualisasikan hasil clustering agar pola dan distribusi data dapat dipahami secara intuitif. Visualisasi pertama menggunakan countplot untuk menampilkan jumlah data pada setiap cluster, sehingga dapat diketahui apakah pembagian cluster seimbang atau tidak. Visualisasi kedua menggunakan scatter plot berbasis PCA1 dan PCA2, yang merupakan hasil reduksi dimensi dari PCA, untuk menampilkan sebaran data dua dimensi dengan warna berbeda sesuai cluster hasil Agglomerative Clustering.


Berdasarkan grafik Distribusi Data per Cluster, terlihat bahwa data terbagi ke dalam tiga cluster, dengan Cluster 0 memiliki jumlah data paling banyak, diikuti oleh Cluster 2, dan Cluster 1 sebagai cluster dengan jumlah data paling sedikit. Hal ini menunjukkan bahwa segmentasi data tidak sepenuhnya seimbang, namun tetap wajar dalam proses clustering. Pada grafik Visualisasi Clustering (Agglomerative) berbasis PCA, terlihat bahwa masing-masing cluster memiliki pola sebaran yang relatif berbeda, meskipun terdapat sedikit tumpang tindih antar cluster. Secara keseluruhan, visualisasi ini menunjukkan bahwa proses Agglomerative Clustering berhasil mengelompokkan data ke dalam beberapa segmen yang dapat dibedakan secara visual, sehingga mendukung hasil analisis clustering dan regresi yang telah dilakukan sebelumnya.

Interpretasi Makna Tiap Cluster
Cluster 0 – Pelanggan Umum

Cluster 0 merupakan kelompok dengan jumlah data paling banyak. Hal ini menunjukkan bahwa cluster ini mewakili pola pembelian tiket yang paling sering terjadi. Transaksi dalam cluster ini umumnya berada pada kisaran harga dan jumlah tiket yang normal atau menengah. Dari sisi bisnis, cluster ini dapat dianggap sebagai pelanggan umum atau reguler yang melakukan pembelian tiket secara rutin dan menjadi penyumbang utama jumlah transaksi.


Cluster 1 – Pelanggan dengan Pola Khusus

Cluster 1 memiliki jumlah data paling sedikit, namun pola datanya relatif lebih seragam. Hal ini menunjukkan bahwa transaksi dalam cluster ini memiliki karakteristik yang lebih spesifik, misalnya harga tiket yang lebih tinggi atau jenis layanan tertentu. Dalam konteks bisnis, cluster ini dapat diartikan sebagai pelanggan dengan kebutuhan khusus atau segmen premium, yang meskipun jumlahnya tidak banyak, namun berpotensi memberikan nilai transaksi yang lebih besar.


Cluster 2 – Pelanggan dengan Perilaku Beragam

Cluster 2 memiliki jumlah data yang cukup besar dengan pola transaksi yang lebih bervariasi. Hal ini menandakan bahwa pelanggan dalam cluster ini memiliki perilaku pembelian yang tidak seragam, baik dari sisi harga maupun jumlah tiket. Dari sudut pandang bisnis, cluster ini dapat dikategorikan sebagai pelanggan yang lebih sensitif terhadap harga atau promosi, sehingga strategi diskon atau penawaran khusus dapat lebih efektif untuk segmen ini.
"""