# -*- coding: utf-8 -*-
"""FINAL DM _NUR FAIZAH AZ ZAHRAH.ipynb

“Analisis Segmentasi Penjualan Tiket Pesawat Menggunakan Agglomerative Clustering dan Ensemble Regression(Ridge, Lasso, dan ElasticNet”

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IX8lbzF95uGoxROcmnZOAcr0bcS4hb_a
"""

# Import library
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.cluster import AgglomerativeClustering
from sklearn.decomposition import PCA
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, r2_score

"""Pada bagian awal Kode ini berfungsi untuk mengimpor dan menyiapkan library yang dibutuhkan dalam proses analisis data, mulai dari pengolahan dan pembersihan dataset menggunakan pandas dan NumPy, pembuatan visualisasi dengan Matplotlib dan Seaborn, tahap praproses data seperti encoding dan scaling, penerapan Agglomerative Clustering untuk pengelompokan data, penggunaan PCA untuk visualisasi hasil clustering, penerapan ensemble regression menggunakan Ridge, Lasso, dan ElasticNet, serta evaluasi performa model regresi menggunakan metrik Mean Squared Error (MSE) dan R² Score."""


# CONFIG STREAMLIT
# =====================================================
st.set_page_config(page_title="UAS Data Mining", layout="wide")
st.title("Clustering + Ensemble Regression")
st.write("Agglomerative Clustering dan Ensemble Regression (Ridge, Lasso, ElasticNet)")

# LOAD DATA (GOOGLE COLAB)
uploaded_file = st.file_uploader(
    "Upload dataset CSV (penjualan tiket pesawat)",
    type=["csv"]
)

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)

    st.subheader("Data Awal")
    st.dataframe(df.head())
else:
    st.info("Silakan upload file CSV untuk memulai analisis.")

"""Kode ini berfungsi untuk membaca dataset `penjualan_tiket_pesawat.csv` dari penyimpanan lokal Google Colab ke dalam sebuah DataFrame menggunakan Pandas, kemudian menampilkan lima baris pertama data sebagai gambaran awal struktur, isi kolom, dan contoh nilai pada dataset sebelum dilakukan proses pembersihan, analisis, clustering, maupun regresi.

"""

# 1. DATA CLEANING
st.subheader("Data Cleaning")

# Ukuran data awal
st.write("Ukuran data awal:", df.shape)

# Missing value
st.write("Missing value per kolom:")
st.write(df.isnull().sum())

# Jumlah data duplikat sebelum dihapus
jumlah_duplikat = df.duplicated().sum()
st.write("Jumlah data duplikat sebelum cleaning:", jumlah_duplikat)

# Hapus data duplikat
df = df.drop_duplicates()

# Tampilkan informasi penghapusan duplikat
st.write("Jumlah data duplikat setelah cleaning:", df.duplicated().sum())

# Konversi kolom Date ke datetime
if "Date" in df.columns:
    df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
st.subheader("Contoh data kolom Date setelah konversi ke datetime")


df_date_tampil = df[["Date"]].copy()
df_date_tampil["Date"] = df_date_tampil["Date"].dt.strftime("%Y-%m-%d %H:%M:%S")

st.dataframe(df_date_tampil.head())
st.write("Ukuran data setelah cleaning:", df.shape)


"""Kode data cleaning tersebut digunakan untuk mengevaluasi dan memastikan kualitas dataset sebelum dilakukan analisis lebih lanjut, dengan cara menampilkan ukuran data awal, memeriksa jumlah missing value pada setiap kolom, mengecek keberadaan data duplikat, menghapus data duplikat jika ada, serta mengonversi kolom Date ke format datetime agar sesuai untuk analisis. Setelah proses pembersihan dilakukan, kode kembali menampilkan kondisi data untuk memastikan tidak ada perubahan yang tidak diinginkan, lalu menyimpan dataset hasil pembersihan ke dalam file data_cleaned.csv sebagai data siap olah.


Pada tahap Data Cleaning tersebut, beberapa langkah pembersihan dan pengecekan kualitas data dilakukan untuk memastikan dataset siap dianalisis. Pertama, ditampilkan ukuran data awal untuk mengetahui jumlah baris dan kolom sebelum proses pembersihan. Selanjutnya, dilakukan pemeriksaan missing value pada setiap kolom menggunakan df.isnull().sum() untuk memastikan tidak ada nilai kosong yang dapat memengaruhi hasil analisis. Setelah itu, data duplikat dihapus menggunakan drop_duplicates() agar tidak terjadi pengulangan data yang dapat menimbulkan bias. Kemudian, jika terdapat kolom Date, nilainya dikonversi ke format datetime agar dapat digunakan dengan benar pada proses analisis lanjutan, seperti feature engineering berbasis waktu. Terakhir, ditampilkan kembali ukuran data setelah cleaning untuk memastikan bahwa proses pembersihan telah berjalan dengan baik dan untuk melihat apakah terjadi perubahan jumlah data.
"""


# 2. ENCODING DATA KATEGORIK
st.subheader("Encoding Data Kategorik")

df_encoded = df.copy()
encoder = LabelEncoder()
for col in df_encoded.select_dtypes(include="object").columns:
    df_encoded[col] = encoder.fit_transform(df_encoded[col])

st.write("Contoh 5 baris data setelah encoding:")
st.dataframe(df_encoded.head())

st.download_button(
    label="Download Data Encoding",
    data=df_encoded.to_csv(index=False),
    file_name="data_encoded.csv",
    mime="text/csv"
)


"""Kode ini digunakan untuk melakukan encoding pada data kategorik, yaitu mengubah nilai bertipe object (seperti teks atau kategori) menjadi nilai numerik agar dapat diproses oleh algoritma machine learning. Proses diawali dengan menyalin dataset hasil data cleaning ke dalam variabel df_encoded untuk menjaga data asli tetap utuh. Selanjutnya, setiap kolom bertipe object diubah menggunakan LabelEncoder, sehingga setiap kategori unik direpresentasikan dalam bentuk angka. Setelah proses encoding selesai, dataset hasil transformasi disimpan ke dalam file data_encoded.csv sebagai data yang siap digunakan pada tahap scaling, clustering, dan regresi.


Output dari proses ini adalah dataset dengan struktur dan jumlah data yang sama seperti sebelumnya (500 baris dan 9 kolom), namun seluruh kolom kategorik seperti City, Gender, Airline, dan Payment_Method telah diubah menjadi nilai numerik. Perubahan ini tidak memengaruhi jumlah data, hanya mengubah representasi nilai agar sesuai dengan kebutuhan algoritma analisis. File data_encoded.csv yang dihasilkan menjadi bukti bahwa data kategorik telah berhasil dipreproses dan siap digunakan pada tahap pemodelan selanjutnya.
"""


# 3. SCALING DATA (NUMERIC ONLY)
st.subheader("Scaling Data")
datetime_cols = df_encoded.select_dtypes(include=["datetime64[ns]"]).columns
df_numeric = df_encoded.drop(columns=datetime_cols)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_numeric)


"""Pada tahap scaling data, dilakukan pemilihan fitur numerik dengan menghapus kolom bertipe datetime karena tidak dapat diproses langsung oleh algoritma machine learning. Selanjutnya, data numerik dinormalisasi menggunakan StandardScaler agar setiap fitur berada pada skala yang sebanding, sehingga proses perhitungan jarak pada Agglomerative Clustering dapat berjalan secara optimal dan tidak dipengaruhi oleh perbedaan skala antar variabel.
"""


# 4. CLUSTERING
st.subheader("Clustering (Agglomerative)")
n_cluster = st.slider("Pilih jumlah cluster", 2, 5, 3)
cluster_model = AgglomerativeClustering(n_clusters=n_cluster)
df["Cluster"] = cluster_model.fit_predict(X_scaled)
st.write("Distribusi Cluster:")
st.write(df["Cluster"].value_counts())


"""Kode ini digunakan untuk melakukan proses clustering pada data penjualan tiket pesawat menggunakan algoritma Agglomerative Clustering. Pengguna dapat menentukan jumlah cluster secara interaktif melalui slider pada aplikasi Streamlit. Data yang telah melalui tahap preprocessing kemudian dikelompokkan berdasarkan tingkat kemiripan karakteristiknya, dan hasil clustering disimpan dalam kolom baru bernama Cluster pada dataset.

Output dari kode ini berupa pembagian data ke dalam beberapa cluster sesuai jumlah yang dipilih pengguna, di mana setiap baris data memiliki label cluster tertentu (misalnya cluster 0, 1, atau 2). Selain itu, ditampilkan juga distribusi jumlah data pada setiap cluster, sehingga pengguna dapat melihat seberapa banyak data yang masuk ke masing-masing kelompok hasil clustering.
"""


# 5. PCA UNTUK VISUALISASI CLUSTER
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
df["PCA1"] = X_pca[:, 0]
df["PCA2"] = X_pca[:, 1]
fig1, ax1 = plt.subplots()
sns.scatterplot(
        x="PCA1",
        y="PCA2",
        hue="Cluster",
        data=df,
        palette="Set2",
        ax=ax1
    )
ax1.set_title("Visualisasi Clustering (PCA)")
st.pyplot(fig1)



"""Kode ini digunakan untuk melakukan reduksi dimensi data menggunakan Principal Component Analysis (PCA) dengan tujuan utama mempermudah visualisasi hasil clustering. PCA mereduksi data berdimensi tinggi menjadi dua komponen utama (PCA1 dan PCA2) yang tetap mempertahankan informasi variansi terbesar dari data asli. Hasil transformasi tersebut kemudian disimpan ke dalam DataFrame sebagai dua kolom baru, sehingga data dapat divisualisasikan dalam bentuk grafik dua dimensi tanpa menghilangkan pola utama yang terbentuk dari proses clustering.


Output dari proses ini adalah dua kolom baru, yaitu PCA1 dan PCA2, yang masing-masing merepresentasikan komponen utama pertama dan kedua dari hasil reduksi dimensi. Kedua kolom ini tidak mengubah jumlah baris data, melainkan hanya menambahkan informasi baru untuk keperluan visualisasi. Dengan adanya PCA1 dan PCA2, hasil clustering dapat divisualisasikan dalam bentuk scatter plot dua dimensi sehingga pemisahan antar cluster dapat diamati secara lebih jelas dan intuitif.
"""


# FEATURE ENGINEERING DARI DATE
if "Date" in df.columns and pd.api.types.is_datetime64_any_dtype(df["Date"]):
    df["Month"] = df["Date"].dt.month
    df["Day"] = df["Date"].dt.day
    df["DayOfWeek"] = df["Date"].dt.dayofweek

    st.subheader("Visualisasi Fitur Waktu")

    col1, col2, col3 = st.columns(3)

    # Distribusi Bulan
    with col1:
        fig_m, ax_m = plt.subplots()
        sns.countplot(x="Month", data=df, ax=ax_m)
        ax_m.set_title("Distribusi Transaksi per Bulan")
        ax_m.set_xlabel("Bulan")
        ax_m.set_ylabel("Jumlah Data")
        st.pyplot(fig_m)

    # Distribusi Hari
    with col2:
        fig_d, ax_d = plt.subplots()
        sns.countplot(x="Day", data=df, ax=ax_d)
        ax_d.set_title("Distribusi Transaksi per Hari")
        ax_d.set_xlabel("Hari")
        ax_d.set_ylabel("Jumlah Data")
        st.pyplot(fig_d)

    # Distribusi Hari dalam Minggu
    with col3:
        fig_w, ax_w = plt.subplots()
        sns.countplot(x="DayOfWeek", data=df, ax=ax_w)
        ax_w.set_title("Distribusi Transaksi per Hari dalam Minggu")
        ax_w.set_xlabel("Hari ke- (0=Senin)")
        ax_w.set_ylabel("Jumlah Data")
        st.pyplot(fig_w)



# 6. ENSEMBLE REGRESSION (RIDGE + LASSO + ELASTICNET)
target_column = "Ticket_Quantity"
ensemble_results = []
train_data = {}
test_data = {}

for cluster in sorted(df["Cluster"].unique()):
    data_cluster = df[df["Cluster"] == cluster]

    if len(data_cluster) < 10:
        continue

    # Split fitur & target
    X = data_cluster.drop(
        columns=[target_column, "Cluster", "PCA1", "PCA2"],
        errors="ignore"
    )
    y = data_cluster[target_column]

    X = X.select_dtypes(include=[np.number])

    # Train-Test Split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    # Simpan Train & Test
    train_df = X_train.copy()
    train_df[target_column] = y_train.values

    test_df = X_test.copy()
    test_df[target_column] = y_test.values

    train_data[cluster] = train_df
    test_data[cluster] = test_df

    # Model Ensemble
    ridge = Ridge(alpha=1.0)
    lasso = Lasso(alpha=0.01)
    elastic = ElasticNet(alpha=0.01, l1_ratio=0.5)

    ridge.fit(X_train, y_train)
    lasso.fit(X_train, y_train)
    elastic.fit(X_train, y_train)

    # Prediksi Ensemble
    y_pred = (
        ridge.predict(X_test)
        + lasso.predict(X_test)
        + elastic.predict(X_test)
    ) / 3

    # Evaluasi
    ensemble_results.append({
        "Cluster": cluster,
        "Jumlah_Data": len(data_cluster),
        "MSE": mean_squared_error(y_test, y_pred),
        "R2_Score": r2_score(y_test, y_pred)
    })




st.subheader("Download Data Train & Test per Cluster")

for cluster in train_data.keys():
    st.download_button(
        label=f"Download Train Cluster {cluster}",
        data=train_data[cluster].to_csv(index=False),
        file_name=f"train_cluster_{cluster}.csv",
        mime="text/csv"
    )

    st.download_button(
        label=f"Download Test Cluster {cluster}",
        data=test_data[cluster].to_csv(index=False),
        file_name=f"test_cluster_{cluster}.csv",
        mime="text/csv"
    )

ensemble_regression_df = pd.DataFrame(ensemble_results)

st.subheader("Hasil Ensemble Regresi per Cluster")
st.dataframe(ensemble_regression_df)


"""Kode ini digunakan untuk melakukan ensemble regression pada setiap cluster hasil clustering, dengan tujuan memprediksi nilai Ticket_Price secara lebih stabil dan akurat. Proses dimulai dengan memisahkan data berdasarkan label cluster, kemudian untuk setiap cluster dilakukan pemodelan regresi menggunakan tiga algoritma regresi berbeda, yaitu Ridge, Lasso, dan ElasticNet, tanpa menggunakan Linear Regression. Fitur numerik dipilih sebagai variabel input, sementara Ticket_Price dijadikan sebagai variabel target. Prediksi akhir diperoleh dengan cara merata-ratakan hasil prediksi dari ketiga model regresi (ensemble averaging), sehingga dapat mengurangi bias dari satu model tunggal. Kinerja model kemudian dievaluasi menggunakan Mean Squared Error (MSE) dan R² Score.


Pada Cluster 0, terdapat 202 data dengan nilai R² sebesar 0,8033, yang menunjukkan bahwa sekitar 80% variasi harga tiket pada cluster ini dapat dijelaskan oleh model regresi. Nilai MSE yang relatif besar menunjukkan adanya variasi harga yang cukup tinggi dalam cluster ini, sehingga tingkat kesalahan prediksi masih cukup signifikan meskipun model sudah mampu menangkap pola umum data.
Cluster 1 memiliki 122 data dan menunjukkan performa terbaik, dengan R² sebesar 0,9719 dan nilai MSE yang paling kecil dibandingkan cluster lainnya. Hal ini mengindikasikan bahwa model ensemble regression sangat baik dalam memprediksi harga tiket pada cluster ini. Pola data yang lebih homogen menyebabkan hubungan antara variabel input dan harga tiket dapat dimodelkan secara lebih akurat.
Sementara itu, Cluster 2 terdiri dari 176 data dengan nilai R² sebesar 0,7653, yang berarti sekitar 76% variasi harga tiket dapat dijelaskan oleh model. Nilai MSE yang cukup besar menunjukkan bahwa karakteristik data pada cluster ini lebih beragam, sehingga tingkat kesalahan prediksi lebih tinggi dibandingkan Cluster 1, namun masih dalam kategori performa yang cukup baik.
Secara keseluruhan, hasil ini menunjukkan bahwa penerapan ensemble regression mampu memberikan performa prediksi yang baik pada setiap cluster, dengan akurasi yang bervariasi tergantung pada karakteristik masing-masing cluster. Pendekatan ini efektif karena mengombinasikan beberapa model regresi, sehingga hasil prediksi menjadi lebih stabil dan tidak bergantung pada satu model tunggal.
"""




# 7. VISUALISASI OUTPUT
# Distribusi data per cluster
st.subheader("Visualisasi Distribusi Data per Cluster")

fig, ax = plt.subplots(figsize=(6,4))
sns.countplot(x="Cluster", data=df, palette="Set2", ax=ax)
ax.set_title("Distribusi Data per Cluster")
ax.set_xlabel("Cluster")
ax.set_ylabel("Jumlah Data")
st.pyplot(fig)

# DOWNLOAD OUTPUT
st.subheader("Download Output")

st.download_button(
    "Download Hasil Clustering + Regresi",
    data=df.to_csv(index=False),
    file_name="hasil_clustering_ensemble_regresi.csv",
    mime="text/csv"
)





"""Kode ini digunakan untuk memvisualisasikan hasil clustering agar pola dan distribusi data dapat dipahami secara intuitif. Visualisasi pertama menggunakan countplot untuk menampilkan jumlah data pada setiap cluster, sehingga dapat diketahui apakah pembagian cluster seimbang atau tidak. Visualisasi kedua menggunakan scatter plot berbasis PCA1 dan PCA2, yang merupakan hasil reduksi dimensi dari PCA, untuk menampilkan sebaran data dua dimensi dengan warna berbeda sesuai cluster hasil Agglomerative Clustering.


Berdasarkan grafik Distribusi Data per Cluster, terlihat bahwa data terbagi ke dalam tiga cluster, dengan Cluster 0 memiliki jumlah data paling banyak, diikuti oleh Cluster 2, dan Cluster 1 sebagai cluster dengan jumlah data paling sedikit. Hal ini menunjukkan bahwa segmentasi data tidak sepenuhnya seimbang, namun tetap wajar dalam proses clustering. Pada grafik Visualisasi Clustering (Agglomerative) berbasis PCA, terlihat bahwa masing-masing cluster memiliki pola sebaran yang relatif berbeda, meskipun terdapat sedikit tumpang tindih antar cluster. Secara keseluruhan, visualisasi ini menunjukkan bahwa proses Agglomerative Clustering berhasil mengelompokkan data ke dalam beberapa segmen yang dapat dibedakan secara visual, sehingga mendukung hasil analisis clustering dan regresi yang telah dilakukan sebelumnya.

Interpretasi Makna Tiap Cluster
Cluster 0 – Pelanggan Umum

Cluster 0 merupakan kelompok dengan jumlah data paling banyak. Hal ini menunjukkan bahwa cluster ini mewakili pola pembelian tiket yang paling sering terjadi. Transaksi dalam cluster ini umumnya berada pada kisaran harga dan jumlah tiket yang normal atau menengah. Dari sisi bisnis, cluster ini dapat dianggap sebagai pelanggan umum atau reguler yang melakukan pembelian tiket secara rutin dan menjadi penyumbang utama jumlah transaksi.


Cluster 1 – Pelanggan dengan Pola Khusus

Cluster 1 memiliki jumlah data paling sedikit, namun pola datanya relatif lebih seragam. Hal ini menunjukkan bahwa transaksi dalam cluster ini memiliki karakteristik yang lebih spesifik, misalnya harga tiket yang lebih tinggi atau jenis layanan tertentu. Dalam konteks bisnis, cluster ini dapat diartikan sebagai pelanggan dengan kebutuhan khusus atau segmen premium, yang meskipun jumlahnya tidak banyak, namun berpotensi memberikan nilai transaksi yang lebih besar.


Cluster 2 – Pelanggan dengan Perilaku Beragam

Cluster 2 memiliki jumlah data yang cukup besar dengan pola transaksi yang lebih bervariasi. Hal ini menandakan bahwa pelanggan dalam cluster ini memiliki perilaku pembelian yang tidak seragam, baik dari sisi harga maupun jumlah tiket. Dari sudut pandang bisnis, cluster ini dapat dikategorikan sebagai pelanggan yang lebih sensitif terhadap harga atau promosi, sehingga strategi diskon atau penawaran khusus dapat lebih efektif untuk segmen ini.
"""